// Generated by CoffeeScript 1.6.2
(function() {
  (function($) {
    var $el, DICTIONARY, LANG_FROM, LANG_TO, SOME_CODE, TRANSLATION, WORD, getUrl, loadWords, onLoadWords, words, _ref;

    $el = $('<div>');
    words = [];
    _ref = [0, 1, 2, 3, 4, 5], LANG_FROM = _ref[0], LANG_TO = _ref[1], SOME_CODE = _ref[2], WORD = _ref[3], TRANSLATION = _ref[4], DICTIONARY = _ref[5];
    getUrl = function(notebookId) {
      if (notebookId == null) {
        notebookId = 0;
      }
      return "/~p/" + (encodeURIComponent('~тетрадки')) + "/" + notebookId;
    };
    loadWords = function(notebookId) {
      if (notebookId == null) {
        notebookId = 0;
      }
      return $el.load(getUrl(notebookId), {
        rnd: Math.random()
      }, onLoadWords);
    };
    onLoadWords = function() {
      words = $el.find('.b-notebook.i-bem').data('words');
      return console.log(words);
    };
    return loadWords(1325505601);
  })(jQuery);

}).call(this);
